name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main, feature/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven
      - name: Compile
        run: mvn --batch-mode clean test-compile
      - name: Test
        run: mvn --batch-mode jacoco:prepare-agent test jacoco:report
      - name: Publish Test Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: 'Test Report'
          report_paths: '**/surefire-reports/TEST-*.xml'